Repository amarbajric/EBUSA-AIM17, pull requests merged in 2018-06, with the labels that each got.

#93 User details #51
  CHANGELOG.md
  GUI-dev/package-lock.json
  GUI-dev/src/app/@theme/components/auth/jwt.interceptor.ts
  GUI-dev/src/app/@theme/components/auth/token.interceptor.ts
  GUI-dev/src/app/@theme/components/header/header.component.ts
  GUI-dev/src/app/@theme/providers/backend-server/gateway.ts
  GUI-dev/src/app/@theme/providers/backend-server/serverconfig.ts
  GUI-dev/src/app/@theme/theme.module.ts
  GUI-dev/src/app/pages/pages-routing.module.ts
  GUI-dev/src/app/pages/pages.module.ts
  GUI-dev/src/app/pages/user-details/user-details.component.html
  GUI-dev/src/app/pages/user-details/user-details.component.scss
  GUI-dev/src/app/pages/user-details/user-details.component.ts
  GUI-dev/src/app/pages/user-details/user-details.module.ts
  GUI-dev/src/models/models.ts
Labels: review

#94 Store service #30
  CHANGELOG.md
  ConfigurationService/gradle/wrapper/gradle-wrapper.properties
  EventLogger/gradle/wrapper/gradle-wrapper.properties
  ExternalCommunicator/gradle/wrapper/gradle-wrapper.properties
  GUI/gradle/wrapper/gradle-wrapper.properties
  Gateway/gradle/wrapper/gradle-wrapper.properties
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/config/GatewayConfig.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/controller/ProcessStoreGatewayController.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/services/impl/ProcessStoreCallerImpl.java
  Gateway/src/main/resources/application.yml
  ProcessEngine/gradle/wrapper/gradle-wrapper.properties
  ProcessModelStorage/gradle/wrapper/gradle-wrapper.properties
  ProcessStore/.gitignore
  ProcessStore/build.gradle
  ProcessStore/gradle/wrapper/gradle-wrapper.jar
  ProcessStore/gradlew
  ProcessStore/settings.gradle
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/ProcessStoreApplication.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/controller/ProcessStoreController.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/Builder.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/entities/ProcessStoreBuilder.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/entities/ProcessStoreObjectImpl.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/objects/ProcessStoreObject.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/repositories/ProcessStore.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessStoreService.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessStoreServiceImpl.java
  ProcessStore/src/main/resources/application.properties
  ProcessStore/src/main/resources/bootstrap.properties
  ProcessStore/src/test/java/at/fhjoanneum/ippr/processstore/ProcessStoreObjectApplicationTests.java
  ServiceDiscovery/gradle/wrapper/gradle-wrapper.properties
  Setup/start_unix/start.sh
  Setup/start_unix/start_process_store.sh
  Setup/start_windows/start.bat
  Setup/start_windows/start_process_store.bat
  SpringCommons/src/main/java/at/fhjoanneum/ippr/commons/dto/processstore/ProcessStoreDTO.java
  SpringCommons/src/main/java/at/fhjoanneum/ippr/commons/global/ServiceIdentifiers.java
Labels: backend

#92 Rbac adaptations #83
  CHANGELOG.md
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/controller/OrganizationController.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/repositories/OrganizationRepository.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/repositories/OrganizationRepositoryImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/services/OrganizationService.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/services/impl/OrganizationServiceImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/authentication/memory/AuthenticationServiceMemoryImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/config/RBACConfig.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/controller/UserController.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/persistence/entities/OrganizationBuilder.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/persistence/entities/OrganizationImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/persistence/entities/ProcessStoreImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/persistence/entities/RatingImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/persistence/entities/ReviewImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/persistence/entities/RoleImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/persistence/entities/RuleImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/persistence/entities/UserImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/persistence/objects/Organization.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/rbacmapping/RBACMappingServiceImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/rbacmapping/retrieval/RBACRetrievalService.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/rbacmapping/retrieval/RBACRetrievalServiceImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/registration/RegistrationServiceDatabaseImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/repositories/RBACRepository.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/repositories/RBACRepositoryImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/services/RBACService.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/services/RBACServiceImpl.java
  Gateway/src/main/resources/application.properties
  Gateway/src/main/resources/database_init/roles.csv
  Gateway/src/main/resources/database_init/rules.csv
  Gateway/src/main/resources/database_init/users.csv
  Gateway/src/main/resources/memoryusers/users.csv
Labels: review

#90 Approval view #87
  CHANGELOG.md
  GUI-dev/src/app/pages/approval-details/approval-details.component.html
  GUI-dev/src/app/pages/approval-details/approval-details.component.scss
  GUI-dev/src/app/pages/approval-details/approval-details.component.ts
  GUI-dev/src/app/pages/approval-details/approval-details.module.ts
  GUI-dev/src/app/pages/approval/approval.component.html
  GUI-dev/src/app/pages/approval/approval.component.scss
  GUI-dev/src/app/pages/approval/approval.component.ts
  GUI-dev/src/app/pages/approval/approval.module.ts
  GUI-dev/src/app/pages/pages-menu.ts
  GUI-dev/src/app/pages/pages-routing.module.ts
  GUI-dev/src/app/pages/pages.module.ts
  GUI-dev/src/models/models.ts
Labels: SWD, frontend, review

#96 Store service #30
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/controller/ProcessStoreGatewayController.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/controller/user/HttpHeaderUser.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/services/impl/ProcessStoreCallerImpl.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/controller/ProcessStoreController.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/entities/ProcessStoreBuilder.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/entities/ProcessStoreObjectImpl.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/repositories/ProcessStore.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessStoreService.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessStoreServiceImpl.java
  SpringCommons/src/main/java/at/fhjoanneum/ippr/commons/dto/processstore/ProcessStoreDTO.java
Labels: review

#91 Processstore - Search component #46
  CHANGELOG.md
  GUI-dev/package-lock.json
  GUI-dev/package.json
  GUI-dev/src/app/@theme/providers/backend-server/gateway.ts
  GUI-dev/src/app/@theme/providers/backend-server/serverconfig.ts
  GUI-dev/src/app/@theme/styles/styles.scss
  GUI-dev/src/app/app.module.ts
  GUI-dev/src/app/pages/pages-menu.ts
  GUI-dev/src/app/pages/pages-routing.module.ts
  GUI-dev/src/app/pages/pages.module.ts
  GUI-dev/src/app/pages/processstore-search/processstore-search.component.html
  GUI-dev/src/app/pages/processstore-search/processstore-search.component.scss
  GUI-dev/src/app/pages/processstore-search/processstore-search.component.ts
  GUI-dev/src/app/pages/processstore-search/processstore-search.module.ts
  GUI-dev/src/app/simple-search.pipe.ts
  GUI-dev/src/assets/images/star-rating.icons.svg
  GUI-dev/src/models/models.ts
  ProcessStore/gradle/wrapper/gradle-wrapper.properties
  ProcessStore/gradlew.bat
Labels: review

#97 User details #51
  CHANGELOG.md
  GUI-dev/package-lock.json
  GUI-dev/src/app/@theme/components/header/header.component.html
  GUI-dev/src/app/app.module.ts
  GUI-dev/src/app/pages/pages-routing.module.ts
  GUI-dev/src/app/pages/pages.module.ts
  GUI-dev/src/app/pages/user-details/user-details.component.html
  GUI-dev/src/app/pages/user-details/user-details.component.ts
  GUI-dev/src/models/models.ts
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/rbacmapping/retrieval/RBACRetrievalServiceImpl.java~HEAD
Labels: review

#98 added rating component (and small process details page) #86
  CHANGELOG.md
  GUI-dev/src/app/@theme/providers/backend-server/gateway.ts
  GUI-dev/src/app/@theme/providers/backend-server/serverconfig.ts
  GUI-dev/src/app/pages/includes/process-ratings/process-ratings.component.html
  GUI-dev/src/app/pages/includes/process-ratings/process-ratings.component.scss
  GUI-dev/src/app/pages/includes/process-ratings/process-ratings.component.ts
  GUI-dev/src/app/pages/includes/process-ratings/process-ratings.module.ts
  GUI-dev/src/app/pages/pages-routing.module.ts
  GUI-dev/src/app/pages/pages.module.ts
  GUI-dev/src/app/pages/processstore-details/processstore-details.component.html
  GUI-dev/src/app/pages/processstore-details/processstore-details.component.scss
  GUI-dev/src/app/pages/processstore-details/processstore-details.component.ts
  GUI-dev/src/app/pages/processstore-details/processstore-details.module.ts
  GUI-dev/src/models/models.ts
Labels: review

#99 adding api docu
  GUI-dev/src/app/@theme/styles/styles.scss
  GUI-dev/src/app/pages/processstore-search/processstore-search.component.scss
  api-documentation/backend-api.yaml
Labels: review

#110 logo/favicon integration
  CHANGELOG.md
  GUI-dev/src/app/@theme/components/header/header.component.html
  GUI-dev/src/app/@theme/components/header/header.component.scss
  GUI-dev/src/assets/easybizlogo.png
  GUI-dev/src/assets/images/test.png
  GUI-dev/src/favicon.ico
  GUI-dev/src/favicon.ico.old
  GUI-dev/src/favicon.png
  GUI-dev/src/favicon.png.old
  GUI-dev/src/index.html
Labels: review

#112 Processstore search component #46 #101
  CHANGELOG.md
  GUI-dev/src/app/@theme/providers/backend-server/gateway.ts
  GUI-dev/src/app/@theme/styles/styles.scss
  GUI-dev/src/app/pages/processstore-search/processstore-search.component.html
  GUI-dev/src/app/pages/processstore-search/processstore-search.component.scss
  GUI-dev/src/app/pages/processstore-search/processstore-search.component.ts
  GUI-dev/src/app/pages/processstore-search/processstore-search.module.ts
  GUI-dev/src/app/process-filter.pipe.ts
  GUI-dev/src/models/models.ts
Labels: review

#109 Create Org & Add user to org - Roles bug fix
  GUI-dev/src/app/@theme/styles/styles.scss
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/controller/OrganizationController.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/services/OrganizationService.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/services/impl/OrganizationServiceImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/controller/UserController.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/persistence/entities/UserImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/repositories/RBACRepository.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/repositories/RBACRepositoryImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/services/RBACService.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/security/services/RBACServiceImpl.java
Labels: review

#113 Store service #30
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/controller/ProcessStoreGatewayController.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/repositories/OrganizationRepositoryImpl.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/services/impl/ProcessStoreCallerImpl.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/controller/ProcessRatingController.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/controller/ProcessStoreController.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/entities/ProcessRatingBuilder.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/entities/ProcessRatingObjectImpl.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/entities/ProcessStoreObjectImpl.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/objects/ProcessRatingObject.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/objects/ProcessStoreObject.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/repositories/ProcessRating.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/repositories/ProcessStore.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessRatingService.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessRatingServiceImpl.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessStoreService.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessStoreServiceImpl.java
  SpringCommons/src/main/java/at/fhjoanneum/ippr/commons/dto/processstore/ProcessRatingDTO.java
  SpringCommons/src/main/java/at/fhjoanneum/ippr/commons/dto/processstore/ProcessStoreDTO.java
Labels: review

#115 Store service #30 - Upload/Download Process File
  CHANGELOG.md
  Gateway/build.gradle
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/controller/ProcessStoreGatewayController.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/services/impl/ProcessStoreCallerImpl.java
  Gateway/src/main/resources/application.properties
  ProcessStore/build.gradle
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/controller/ProcessStoreController.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/entities/ProcessOrgaMappingObjectImpl.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/entities/ProcessStoreBuilder.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/entities/ProcessStoreObjectImpl.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/objects/ProcessOrgaMappingObject.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/repositories/ProcessOrgaMapping.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/repositories/ProcessStore.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessOrgaMappingService.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessOrgaMappingServiceImpl.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessStoreService.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessStoreServiceImpl.java
  ProcessStore/src/main/resources/application.properties
  SpringCommons/src/main/java/at/fhjoanneum/ippr/commons/dto/processstore/ProcessOrgaMappingDTO.java
  SpringCommons/src/main/java/at/fhjoanneum/ippr/commons/dto/processstore/ProcessStoreDTO.java
Labels: review

#118 Dummy test data sql script
  ebusa_testdata_v1.sql
Labels: review

#121 Store service #30 - Create Orga & Get AvgRatingAndCount
  Gateway/gradle/wrapper/gradle-wrapper.properties
  Gateway/gradlew.bat
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/controller/ProcessStoreGatewayController.java
  Gateway/src/main/java/at/fhjoanneum/ippr/gateway/api/services/impl/ProcessStoreCallerImpl.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/controller/ProcessRatingController.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/controller/ProcessStoreController.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/persistence/entities/ProcessStoreObjectImpl.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/repositories/ProcessStore.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessStoreService.java
  ProcessStore/src/main/java/at/fhjoanneum/ippr/processstore/services/ProcessStoreServiceImpl.java
  SpringCommons/src/main/java/at/fhjoanneum/ippr/commons/dto/processstore/ProcessAvgRatingDTO.java
Labels: backend, review

#120 Process details #49
  CHANGELOG.md
  GUI-dev/package-lock.json
  GUI-dev/src/app/@theme/providers/backend-server/gateway.ts
  GUI-dev/src/app/@theme/providers/backend-server/serverconfig.ts
  GUI-dev/src/app/pages/processstore-details/modal/processstore-details.modal.ts
  GUI-dev/src/app/pages/processstore-details/processstore-details.component.html
  GUI-dev/src/app/pages/processstore-details/processstore-details.component.scss
  GUI-dev/src/app/pages/processstore-details/processstore-details.component.ts
  GUI-dev/src/app/pages/processstore-details/processstore-details.module.ts
  GUI-dev/src/assets/images/exampleProcess.jpg
  GUI-dev/src/models/models.ts
  SpringCommons/src/main/java/at/fhjoanneum/ippr/commons/dto/processstore/ProcessStoreDTO.java
Labels: review

#117 Approval view ref #100
  CHANGELOG.md
  GUI-dev/package-lock.json
  GUI-dev/package.json
  GUI-dev/src/app/@theme/components/auth/register/register.component.ts
  GUI-dev/src/app/@theme/providers/backend-server/gateway.ts
  GUI-dev/src/app/@theme/providers/backend-server/serverconfig.ts
  GUI-dev/src/app/app.module.ts
  GUI-dev/src/app/approval-auth-guard.service.ts
  GUI-dev/src/app/pages/approval-details/approval-details.component.html
  GUI-dev/src/app/pages/approval-details/approval-details.component.ts
  GUI-dev/src/app/pages/approval-details/approval-details.module.ts
  GUI-dev/src/app/pages/approval/approval.component.html
  GUI-dev/src/app/pages/approval/approval.component.ts
  GUI-dev/src/app/pages/approval/approval.module.ts
  GUI-dev/src/app/pages/pages-routing.module.ts
  GUI-dev/src/app/pages/processstore-details/processstore-details.component.ts
  GUI-dev/src/models/models.ts
Labels: frontend, review

#123 fixing processstoredto
  SpringCommons/src/main/java/at/fhjoanneum/ippr/commons/dto/processstore/ProcessStoreDTO.java
Labels: review

#116 Integrate Backend in Rating component #86 #102
  CHANGELOG.md
  GUI-dev/src/app/@theme/providers/backend-server/gateway.ts
  GUI-dev/src/app/@theme/providers/backend-server/serverconfig.ts
  GUI-dev/src/app/pages/includes/process-ratings/process-ratings.component.html
  GUI-dev/src/app/pages/includes/process-ratings/process-ratings.component.ts
  GUI-dev/src/models/models.ts
Labels: review

#119 Welcomepage #48
  GUI-dev/package-lock.json
  GUI-dev/src/app/@theme/components/header/header.component.ts
  GUI-dev/src/app/@theme/providers/backend-server/gateway.ts
  GUI-dev/src/app/@theme/providers/backend-server/serverconfig.ts
  GUI-dev/src/app/app.component.ts
  GUI-dev/src/app/app.module.ts
  GUI-dev/src/app/pages/home/home.component.html
  GUI-dev/src/app/pages/home/home.component.scss
  GUI-dev/src/app/pages/home/home.component.ts
  GUI-dev/src/index.html
  GUI-dev/src/models/models.ts
  Setup/start_unix/start.sh
Labels: review
